/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface EvidenceAnchorInterface extends Interface {
  getFunction(
    nameOrSignature: "anchor" | "anchoredEvidence" | "verify"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "EvidenceAnchored"): EventFragment;

  encodeFunctionData(
    functionFragment: "anchor",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "anchoredEvidence",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "verify", values: [BytesLike]): string;

  decodeFunctionResult(functionFragment: "anchor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "anchoredEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
}

export namespace EvidenceAnchoredEvent {
  export type InputTuple = [
    caseId: BytesLike,
    evidenceRoot: BytesLike,
    timestamp: BigNumberish,
    submitter: AddressLike
  ];
  export type OutputTuple = [
    caseId: string,
    evidenceRoot: string,
    timestamp: bigint,
    submitter: string
  ];
  export interface OutputObject {
    caseId: string;
    evidenceRoot: string;
    timestamp: bigint;
    submitter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EvidenceAnchor extends BaseContract {
  connect(runner?: ContractRunner | null): EvidenceAnchor;
  waitForDeployment(): Promise<this>;

  interface: EvidenceAnchorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  anchor: TypedContractMethod<
    [evidenceRoot: BytesLike, caseId: BytesLike],
    [void],
    "nonpayable"
  >;

  anchoredEvidence: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, string] & {
        evidenceRoot: string;
        caseId: string;
        timestamp: bigint;
        submitter: string;
      }
    ],
    "view"
  >;

  verify: TypedContractMethod<
    [evidenceRoot: BytesLike],
    [
      [boolean, bigint, string] & {
        exists: boolean;
        timestamp: bigint;
        submitter: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "anchor"
  ): TypedContractMethod<
    [evidenceRoot: BytesLike, caseId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "anchoredEvidence"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, string] & {
        evidenceRoot: string;
        caseId: string;
        timestamp: bigint;
        submitter: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<
    [evidenceRoot: BytesLike],
    [
      [boolean, bigint, string] & {
        exists: boolean;
        timestamp: bigint;
        submitter: string;
      }
    ],
    "view"
  >;

  getEvent(
    key: "EvidenceAnchored"
  ): TypedContractEvent<
    EvidenceAnchoredEvent.InputTuple,
    EvidenceAnchoredEvent.OutputTuple,
    EvidenceAnchoredEvent.OutputObject
  >;

  filters: {
    "EvidenceAnchored(bytes32,bytes32,uint256,address)": TypedContractEvent<
      EvidenceAnchoredEvent.InputTuple,
      EvidenceAnchoredEvent.OutputTuple,
      EvidenceAnchoredEvent.OutputObject
    >;
    EvidenceAnchored: TypedContractEvent<
      EvidenceAnchoredEvent.InputTuple,
      EvidenceAnchoredEvent.OutputTuple,
      EvidenceAnchoredEvent.OutputObject
    >;
  };
}
