/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EvidenceAnchor } from "./EvidenceAnchor";
export * as factories from "./factories";
export { EvidenceAnchor__factory } from "./factories/EvidenceAnchor__factory";
